" start vundle Settings
set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'

" My bundles
"--------------------------------------------------------
Bundle 'git@github.com:altercation/vim-colors-solarized.git'
Bundle 'git@github.com:scrooloose/nerdcommenter.git'
Bundle 'git@github.com:kevinw/pyflakes-vim.git'
Bundle 'git@github.com:Lokaltog/powerline'
set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim/

filetype plugin indent on
" end vundle settings
"--------------------------------------------------------

" Visual settings
syntax enable
set background=dark
colorscheme solarized
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"

" disable blinking cursor
set gcr=a:blinkon0

set guifont=Inconsolata\ 13

" tab settings
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set encoding=utf-8
set autoindent
set number

" show status all the time
set laststatus=2

" set backup dir
set backupdir=~/tmp
