# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="aeon"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# dont store commands starting with space in history
HIST_IGNORE_SPACE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git command-not-found sublime autojump compinit pip virtualenvwrapper virtualenv)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/heroku/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

#-----------------------------------------------------
#-----------------------------------------------------
#-----------------------------------------------------

#======path settings
# http://unix.stackexchange.com/questions/62579/is-there-a-way-to-add-a-directory-to-my-path-in-zsh-only-if-its-not-already-pre
# ensure path array is unique
typeset -U path

# add to front
path=(~/dev/bin "$path[@]")
path=(/home/azaan/.npm/global/bin "$path[@]")

#======custom functions

# sum 1 2 3 4
function sum; {
    sum=0
    for var in "$@"; do
        sum=$((sum + var ))
    done
    echo $sum
}

# average 1 2 3 4
function average; {
    echo $(( $(sum $@) / ($# + 0.0) ))
}

# chrome = opens chrome
function chrome; {
    google-chrome $* > /dev/null 2>&1 &
    disown
}

# sublime foldername
function sublime; {
    nohup "/home/azaan/Software/Sublime Text 2/sublime_text" $* >/dev/null 2>&1 &
}

# domath "sin(2)"
function domath; {
    zmodload zsh/mathfunc
    echo $(( $* ))
}

# URL encode something and print it.
function url-encode; {
    setopt extendedglob
    echo "${${(j: :)@}//(#b)(?)/%$[[##16]##${match[1]}]}"
}

# google hello world
function google; {
    chrome "http://www.google.com/search?q=`url-encode "${(j: :)@}"`"
}

# suspendat 2:40
function suspendat; {
    echo pdbus-send --print-reply --system --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Suspend | at $*
}

# Function to generate gitignore
function gi() { curl http://gitignore.io/api/$@ ;}

#======normal alias

# music settings
export PLAYER=rythmbox
alias rbox="rhythmbox"
alias song="/home/azaan/dev/Rhythmbox-Remote/rhythmRemote.py"
alias sw="song what"
alias sn="song next"
alias sp="song prev"
alias sr="song rate"
alias p="song play"

# open apps
alias chromei="chrome -incognito"
alias openw="nautilus ."
alias termx="gnome-terminal --geometry=90x24+100+50"
alias termy="gnome-terminal --geometry=90x24+500+260"
alias clem="nohup clementine >/dev/null 2>&1 &"
alias burp="nohup java -jar ~/dev/bin/burpsuite_free_v1.5.jar > /dev/null 2>&1 &"

# android alias
alias adb="sudo /home/azaan/Software/android-sdk-linux/platform-tools/adb"
# vim aliases
alias g="gvim"
alias v="vim"

# git aliases
alias gc="git commit --verbose"
alias gca="git commit --verbose -a"
alias gcm="git commit -m"
alias gcam="git commit -am"
alias gd="git d"
alias ga="git add ."
alias gs="git status -s"
alias gl="git log"
alias glo="git log --oneline --graph"
alias gph="git push heroku master"
alias gpo="git push origin master"

alias mv="mv -i" #comfirm on overwrite
alias rm="rm -i"
alias cp="cp -i"

alias pyinstall="sudo python setup.py install"

# xampp server
alias server="sudo /opt/lampp/lampp"

# package management
alias sagi="sudo apt-get install"
alias sagu="sudo apt-get update"
alias saar="sudo add-apt-repository"
# pip
alias spi="sudo pip install"
# npm
alias nig="npm install -g"
alias ni="npm install"

#======suffix alias (if a file with the suffix is run)
alias -s html=vim
alias -s css=vim
alias -s c=vim
alias -s js=vim
alias -s py=python
alias -s sh=zsh

#======global alias (substitute inside another command)
alias -g NUL="> /dev/null 2>&1"

#======zsh options

setopt AUTO_CD

# history options
setopt hist_ignore_space # dont remember commands which start with space
setopt no_hist_verify #! history executes automatically
bindkey "^k" history-search-backward # Up
bindkey "^j" history-search-forward # Down

# Set lang as UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8


# shell helpers
#-----------------------------------------------
export TERM=xterm-256color
alias sz="source ~/.zshrc"
alias zshrc="gvim ~/dev/dotfiles/zsh/zshrc"
alias vimrc="gvim ~/dev/dotfiles/vim/vimrc"

# colorize the shell
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# copy current working directory
alias cwd="pwd | tr -d '\n' | xsel -b"

# show sorted disk usage for current directory
alias dus="du -xksh * | sort -h"

alias pgoogle="ping www.google.com"
alias l="ls -lh"
alias netlogp="sudo nethogs ppp0"
alias netlogw="sudo nethogs wlan0"
alias cc="cd;clear"
alias op="xdg-open"
alias ack="ack-grep"

