# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# ZSH Theme
ZSH_THEME="aeon"
# (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git command-not-found sublime autojump heroku)
plugins+=(compinit pip virtualenvwrapper virtualenv docker)

source $ZSH/oh-my-zsh.sh

#==
# -PATH Settings {
    export PATH=/usr/local/heroku/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

    # http://unix.stackexchange.com/questions/62579/is-there-a-way-to-add-a-directory-to-my-path-in-zsh-only-if-its-not-already-pre

    # ensure path array is unique
    typeset -U path

    # add to front of path
    path=(~/dev/bin "$path[@]")
    path=(/home/azaan/local/bin "$path[@]")
# }

#==
# -Shell Setup {
    export TERM=xterm-256color
    alias sz="source ~/.zshrc"
    alias zshrc="gvim ~/dev/github/dotfiles/zsh/zshrc"
    alias vimrc="gvim ~/dev/github/dotfiles/vim/vimrc"

    # colorize the shell
    if [ -x /usr/bin/dircolors ]; then
        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    fi

    # make grep coloring work well with solarize
    export GREP_COLOR="00;32"

    # Set lang as UTF-8
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LANGUAGE=en_US.UTF-8

    # Set up palm detection
    synclient PalmDetect=1 PalmMinWidth=10 PalmMinZ=20

    #==
    # -ZSH Specific options {
        COMPLETION_WAITING_DOTS="true"

        # cd by typing just path, without cd
        setopt AUTO_CD

        # history options
        HIST_IGNORE_SPACE="true"
        setopt hist_ignore_space # dont remember commands which start with space
        setopt no_hist_verify #! history executes automatically
        bindkey "^k" history-search-backward # Ctrl + k
        bindkey "^j" history-search-forward # Ctrl + j
    # }
# }

#==
# -Modifications to original UNIX commands
    alias l="ls -lhF"
    alias ls="ls -F --color"

    alias RM="\rm -f"

    # -i = make interactice
    alias cp="cp -i"

    # make rm safe, add cron job to empty trash
    alias rm="mv -t ~/.trash"
# }

#==
# -File sffix aliases {
    alias -s html=vim
    alias -s css=vim
    alias -s c=vim
    alias -s js=vim
    alias -s py=python
    alias -s sh=zsh
# }

#==
# -Global aliases {
    alias -g NUL="> /dev/null 2>&1"
# }

#==
# -Shell Helper aliases {
    # mount win partition as rw
    alias mountd="sudo mount -t ntfs -o nls=utf8,uid=azaan,gid=azaan,rw,umask=013 /dev/sda5 /media/Delta"
    alias umountd="sudo umount /media/Delta"

    # copy current working directory to clipboard
    alias cwd="pwd | tr -d '\n' | xsel -b"

    # show sorted disk usage for current directory
    alias dus="du -xksh * | sort -h"

    alias pgoogle="ping www.google.com"

    alias netlogp="sudo nethogs ppp0"
    alias netlogw="sudo nethogs wlan0"

    alias cc="cd;clear"

    alias pyinstall="sudo python setup.py install"
    alias pserver="python -m SimpleHTTPServer"

    #==Package management helpers
    alias sagi="sudo apt-get install"
    alias sagu="sudo apt-get update"
    alias saar="sudo add-apt-repository"
    # pip
    alias pi="pip install"
    # npm
    alias nig="npm install -g"
    alias ni="npm install"


    function sum; {
        sum=0
        for var in "$@"; do
            sum=$((sum + var ))
        done
        echo $sum
    }

    function average; {
        echo $(( $(sum $@) / ($# + 0.0) ))
    }

    function domath; {
        zmodload zsh/mathfunc
        echo $(( $* ))
    }

    function url-encode; {
        setopt extendedglob
        echo "${${(j: :)@}//(#b)(?)/%$[[##16]##${match[1]}]}"
    }

    function google; {
        chrome "http://www.google.com/search?q=`url-encode "${(j: :)@}"`"
    }

    function suspendat; {
        echo pdbus-send --print-reply --system --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Suspend | at $*
    }

    # Generate gitignores
    function gi() { curl http://gitignore.io/api/$@ ;}
# }

#==
# -Open apps
    alias chromei="chrome -incognito"
    alias openw="nautilus ."
    alias termx="gnome-terminal --geometry=90x24+100+50"
    alias termy="gnome-terminal --geometry=90x24+500+260"
    alias burp="nohup java -jar ~/dev/bin/burpsuite_free_v1.5.jar > /dev/null 2>&1 &"
    alias adb="sudo /home/azaan/Software/android-sdk-linux/platform-tools/adb"
    alias g="gvim"
    alias v="vim"
    alias op="xdg-open"
    alias ack="ack-grep"
    alias server="sudo /opt/lampp/lampp"
    alias bower='noglob bower'

    # link to the xampp server
    function xampp-remove; {
        rm -f /opt/lampp/htdocs/s/$*
    }

    function xampp-add; {
        ln -s `pwd`/$* /opt/lampp/htdocs/s/
    }

    function chrome; {
        google-chrome $* > /dev/null 2>&1 &
        disown
    }

    function sublime; {
        nohup "/home/azaan/Software/Sublime Text 2/sublime_text" $* >/dev/null 2>&1 &
    }
# }

#==
# -RhythmRemote settings {
    export PLAYER=rythmbox
    alias rbox="rhythmbox"
    alias song="/home/azaan/dev/github/Rhythmbox-Remote/rhythmRemote.py"
    alias sw="song what"
    alias sn="song next"
    alias sp="song prev"
    alias sr="song rate"
    alias p="song play"
# }

#==
# -Git aliases {
    alias gc="git commit --verbose"
    alias gca="git commit --verbose -a"
    alias gcm="git commit -m"
    alias gcam="git commit -am"
    alias gd="git d"
    alias gdq="git diff"
    alias ga="git add ."
    alias gs="git status -s"
    alias gl="git log --graph --decorate --all --stat"
    alias glo="git log --oneline --graph"

    alias gph="git push heroku master"
    alias gpo="git push origin master"
# }

#==
# -Program settings {
    export VIMRUNTIME=/usr/local/share/vim/vim74
    export NODE_PATH=~/local/lib/nodejs:~/local/lib/node_modules:/usr/share/javascript
# }
