# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# ZSH Theme
ZSH_THEME="robbyrussell"

# (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git docker)

# zsh config
zstyle ':omz:update' frequency 13

source $ZSH/oh-my-zsh.sh

#==
# -PATH Settings {

    # ensure path array is unique
    typeset -U path

    # add to front of path
    path=(~/bin "$path[@]")
    path=(~/.composer/vendor/bin "$path[@]")

# }

#==
# -Shell Setup {
    export EDITOR=vim

    setopt extended_glob
    unsetopt CASE_GLOB
    export TERM=xterm-256color
    alias sz="source ~/.zshrc"
    alias zshrc="$EDITOR ~/work/aznn/dotfiles/zsh/zshrc"

    # colorize the shell
    if [ -x /usr/bin/dircolors ]; then
        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    fi

    # make grep coloring work well with solarize
    export GREP_COLOR="00;32"

    # Set lang as UTF-8
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LANGUAGE=en_US.UTF-8

    #==
    # -ZSH Specific options {
        COMPLETION_WAITING_DOTS="true"

        # cd by typing just path, without cd
        setopt AUTO_CD

        # history options
        HIST_IGNORE_SPACE="true"
        setopt hist_ignore_space # dont remember commands which start with space
        setopt no_hist_verify #! history executes automatically
        bindkey "^k" history-search-backward # Ctrl + k
        bindkey "^j" history-search-forward # Ctrl + j
    # }
# }

#==
# -Modifications to original UNIX commands
    alias l="ls -lhF"
    alias ls="ls -F --color"

    # -i = make interactice
    alias cp="cp -i"
# }

#==
# -File sffix aliases {
    alias -s html=vim
    alias -s css=vim
    alias -s c=vim
    alias -s js=vim
#    alias -s py=python
    alias -s rb=ruby
    alias -s sh=zsh
# }

#==
# -Global aliases {
    alias -g NUL="> /dev/null 2>&1"
## }

#==
# -Shell Helper aliases {
    # copy current working directory to clipboard
    alias cwd="pwd | tr -d '\n' | xsel -b"
    alias copy="xsel -b"

    # show sorted disk usage for current directory
    alias dus="du -xksh * | sort -h"

    alias pgoogle="ping www.google.com"

    alias cc="cd;clear"

    alias pyinstall="sudo python setup.py install"
    alias pserver="python -m SimpleHTTPServer"

    #==Package management helpers

    # pip
    alias pi="pip install"

    # npm
    alias nig="npm install -g"
    alias ni="npm install"

    # grep running processes
    alias pgrep="ps ux | grep -i"

    # Generate gitignores
    function gi() { curl http://gitignore.io/api/$@ ;}

    # search
    alias fname="find . -name"
# }

#==
# -Open apps
    alias v="vim"
    alias op="xdg-open"
    alias py="python"


    # shortcuts for printing awk columns
    function awk1; { awk '{print $1}' }
    function awk2; { awk '{print $2}' }
    function awk4; { awk '{print $4}' }
    function awk5; { awk '{print $5}' }
    function awk6; { awk '{print $6}' }

    # make and cd to dir
    function mdir; {
        mkdir $* && cd $_
    }
# }

#==
# Program aliases {
    # git
    alias ga="git add ."
    alias gc="git commit --verbose"
    alias gca="git commit --verbose -a"
    alias gcA="git add .; gca"
    alias gcm="git commit -m"
    alias gcam="git commit -am"
    alias gcamend="git commit --amend --verbose"
    alias gd="git d"
    alias gdq="git diff"
    alias ga="git add ."
    alias gs="git status -s"
    alias gl="git log --graph --decorate --all --stat --date=relative"
    alias glo="git log --oneline --decorate --graph --abbrev-commit --date=relative --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) [%C(blue)%an%C(reset)] - %C(white)%s%C(reset)'"
    alias gph="git push heroku master"
    alias gpo="git push origin master"
    alias gpoh="gpo && gph"

    # django
    alias manage="py manage.py "
    alias splus="python manage.py runserver_plus"
    alias msm="manage schemamigration"
    alias mm="manage migrate"

    # docker
    alias dc="docker-compose"

    # laravel
    alias erun="envoy run"
    alias art="php artisan"
    alias dcart="docker-compose exec app php artisan $@"
# }
